apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-resource-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "4"
    pods: "2"
    services: "5"
    persistentvolumeclaims: "5"
    secrets: "10"
    configmaps: "10"