apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: mongo
spec:
  selector:
    app: mongo-db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017 #this shld be same with our container port
  type: ClusterIP  