apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wordpress
  name: mysqldb-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql  # Corrected duplicate selector field
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:  # Corrected field name
                  name: mysql-secret #this most match the secre.yaml name
                  key:  mysql_passwd
          ports:
            - containerPort: 3306  # Corrected field name and indentation
