apiVersion: apps/v1
kind: Deployment
metadata:
  name: utc-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
      env: Dev  # This will allow selection of all pods with these labels (nginx, Dev)
  template:
    metadata:
      labels:
        app: nginx
        env: Dev  # This will assign these labels to the pods created by the deployment
    spec:
      containers:
        - name: nginx-container
          image: 455452245698.dkr.ecr.us-east-1.amazonaws.com/devops:20  # Image can be from any registry (e.g., ECR, DockerHub, etc.)
          ports:
            - containerPort: 8082  # Corrected field name (containerPort, not containerport)
      tolerations:
        - key: "color"
          operator: "Equal"
          value: "green"
          effect: "NoSchedule"
      # resources:
      #   limits:  # Maximum resources the container can consume
      #     memory: "150Mi"
      #     cpu: "400m"
      #   requests:  # Resources requested by the container at startup
      #     memory: "150Mi"
      #     cpu: "400m"
