apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: dev
  name: utc-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest # we can use any image ie httpd or  ksege2001/pod-host or from our ECR AWS URL: 455452245698.dkr.ecr.us-east-1.amazonaws.com/devops:20
        resources:    # Sets resource limits and requests for the container (guaranteed, burstable, besteffort   )
          limits: 
            memory: "150Mi"
            cpu: "400m"
          requests:
            memory: "150Mi"
            cpu: "400m"
   
          
