apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      env:
        - name: port_number
          valueFrom:
            configMapKeyRef:
              name:  configmap   # The name of the ConfigMap
              key: port         # The key from the ConfigMap to use
