apiVersion: v1
kind: Service
metadata:
  name: utrain-service
spec:
  selector:
    app: nginx  #this most be same as it is in deploy      # Ensure this label matches the app label on the target pod(s)
  ports:
    - name: utrains-service-port
      protocol: TCP    # Protocol names are uppercase
      port: 80         # Port exposed by the service
      targetPort: 80   # Port on the pod to route traffic to
